config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users do
    resources :participants
  end
  resources :events do
    resources :participants
    resources :draw
    get '/make', to: 'draws#make', as: 'make'
  end

  resources :wishlists do
    resources :items, only: [:new, :create]
  end
end

app/views/shared/_current_user_show.html.erb

<h1 class="section-title">Welcome <%=current_user.first_name%>!</h1>

<div style="display: flex; gap: 24px; flex-direction: column;">
  <h1>Your secret santa events!</h1>
    <% if @mypeople.empty?%>
      <p> You aren't apart of any events </p>
    <% else %>
      <div>

        <div class="event-container">
          <% @mypeople.each do |e| %>
            <div class="card-event">
              <div class="card-event-infos">
                <div style="display: flex; gap: 4px;">
                  <p style="font-weight: bold;">Event: </p>
                  <p><%= e[0]%><p>
                </div>

                <div style="display: flex; gap: 4px;">
                  <p style="font-weight: bold;">Location: <p>
                  <p><%= e[1]%><p>
                </div>

                <div style="display: flex; gap: 4px;">
                  <p style="font-weight: bold;">Date: <p>
                  <p><%= e[6]%><p>
                </div>

                <div style="display: flex; gap: 4px;">
                  <p style="font-weight: bold;">Budget: <p>
                  <p><%= e[2]%><p>
                </div>

                <div style="display: flex; gap: 4px;">
                  <p style="font-weight: bold;">You are Santa to: <p>
                  <p><%= e[3]%><p>
                </div>

                <div style="display: flex; gap: 4px;">
                  <p style="font-weight: bold;">View their wishlist here: </p>
                  <% if e[4] != nil%>
                    <%= link_to e[4].name, wishlist_path(e[5])%>
                  <% else%>
                    <p>They don't have a list 😥</p>
                  <% end%>
                </div>
              </div>
            </div>
          <% end%>
        </div>
      </div>
    <%end%>

  <div style="display: flex; gap: 16px; flex-direction: column;">
    <h1>Your wish list</h1>
    <div>
      <% if @my_wishlists.empty? %>
        <p>You have not made a wishlist</p>
        <%= link_to "Create your wish list", new_wishlist_path, class: "app-button" %>
      <% else %>
        <div>
          <% @my_wishlists.each do |wishlist| %>
            <%= link_to wishlist.name , wishlist_path(wishlist), class:"app-button"%>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div>
    <h1>Events you have created</h1>
    <div class="event-container">
        <%if @my_events.empty?%>
          <p>You have no events</p>
        <% else %>
          <div style="display: flex;">
            <% @my_events.each do |event| %>
              <%= link_to event_path(event), class:"link-event" do %>
                <div class="card-event">
                  <div class="card-event-infos">
                    <div style="display: flex; gap: 4px;">
                      <p style="font-weight: bold;">Event: <p>
                      <p><%= event.name %></p>
                    </div>
                    <div style="display: flex; gap: 4px;">
                      <p style="font-weight: bold;">Date: <p>
                      <p><%= event.date %></p>
                    </div>

                  </div>
                </div>
              <%end %>
            <% end %>
          </div>
        <% end %>
    </div>
  </div>

</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= button_to "Log Out", destroy_user_session_path, method: :delete , class:"logout-btn"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>