config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users do
    resources :participants
  end
  resources :events do
    resources :participants
    resources :draw
    get '/make', to: 'draws#make', as: 'make'
  end

  resources :wishlists do
    resources :items, only: [:new, :create]
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :participants, dependent: :destroy
  has_many :users, through: :participants
  has_many :draws, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2 }
  validates :location, presence: true, length: { minimum: 2 }
  validates :date, presence: true, length: { minimum: 2 }
  validates :price, presence: true, length: { minimum: 2 }, numericality: { only_integer: true }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :destroy, :edit, :update]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @events = Event.all
  end

  def show
    # want to show the participants on the event show page
    @participant = Participant.new
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to event_path(@event)
      flash[:notice] = "event created!"
    else
      flash.now[:alert] = "Sorry, there was an issue!"
      render :new
    end
  end

  def edit
    # get the form
  end

  def update
    # patch the form
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event.destroy
    redirect_to user_path(current_user), status: :see_other
  end

  private

  def event_params
    params.require(:event).permit(
      :name,
      :location,
      :price,
      :date
    )
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/views/events/_form.html.erb
  <%= simple_form_for(@event) do |f| %>
    <%= f.input :name, label: "Event name" %>
    <%= f.input :location %>
    <%= f.input :date %>
    <%= f.input :price, label:"Budget"%>
    <div style='display:flex; justify-content:center;'>
      <%= f.button :submit, class:"app-button" %>
    </div>
  <% end %>

app/views/events/edit.html.erb
  <div class="container">
    <h2>Submit changes to event</h2>
    <%= render "events/form", event: @event %>
    <%= button_to "Back to profile", user_path(current_user) , method: :get, class:"app-button" %>
  </div>

app/views/events/index.html.erb
<div class="container">
  <h1>All events</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Location</th>
        <th>Price</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    <thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.name %></td>
          <td><%= event.location%></td>
          <td><%= event.price%></td>
          <td><%= event.user_id%></td>
        </tr>
      <% end %>
    </tbody>
  <table>

</div>

app/views/events/new.html.erb
<div class="container">
  <div class="section-title">
    <h1>Create your event here</h1>
  </div>
    <%= render "events/form", event: @event %>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="section-title-event">
    <h2><%=@event.name%></h2>
    <div style="display: flex; gap: 4px;">
      <p style="font-weight: bold;">Date: </p>
      <p><%=@event.date%></p>
    </div>
    <div style="display: flex; gap: 4px;">
      <p style="font-weight: bold;">Location: </p>
      <p><%=@event.location%></p>
    </div>
    <div style="display: flex; gap: 4px;">
      <p style="font-weight: bold;">Budget: </p>
      <p><%=@event.price%></p>
    </div>
  </div>

  <h2><%= pluralize @event.participants.size, "participant"%> </h2>
  <div>
    <% if @event.participants.blank? %>
      Add the first participant to <%= @event.name %>
    <% else %>
      <% @event.participants.each do |participant| %>
        <ul>
          <li><p><%= participant.first_name %> <%= participant.last_name %></p>
        <%# <%= participant.email %>
        </ul>
      <% end %>
    <% end %>
  </div>

  <div>
    <% if @event.draws.empty? %>
      <%= simple_form_for([@event, @participant]) do |f| %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :email %>
        <div style='display:flex; justify-content:center;'>
          <%= f.button :submit, class:"app-button" %>
        </div>
      <% end %>
    <% end%>
  </div>
  <br>

  <div style='text-align: center;'>
    <div>
      <% if @event.draws.empty? %>
        <%= button_to "create draws", event_make_path(@event), method: :get, class:"app-button"  %>
      <% end%>
    </div>
    <div style='margin-top: 20px'>
      <%= button_to "Edit event", edit_event_path(@event) , method: :get, class:"app-button" %>
    </div>
    <div style='margin-top: 20px'>
      <%= button_to "Back to profile", user_path(current_user) , method: :get, class:"app-button" %>
    </div>
    <div style='margin-top: 20px'>
      <%= button_to "Delete", event_path(@event) ,form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete, class:"app-button"%>
    </div>
  </div>
</div>